server:
  port: 8767
spring:
  application:
    name: cloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: false


zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-ribbon
    api-b:
      path: /api-b/**
#      serviceId: cloud-feign
#过滤可添加serviceId或者URL
      url: http://192.168.0.84/farm_server/

