server:
  port: 8088
spring:
  application:
    name: cloud-zuul
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 40960KB
      location: /Users/benyuan/spring-cloud/uploadPro
storage:
  location: upload-dir